[package]
name = "wgpu_graphical_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
log = "0.4.22"
anyhow = "1.0.86"
wgpu = "22.0.0"
bytemuck = { version = "1.16.1", features = ["derive"] }
cgmath = "0.18"