[package]
name = "glfw_window_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
anyhow = "1.0.86"
common_gateways_and_adapters = { path = "../common_gateways_and_adapters" }

[dependencies.glfw]
version = "0.58.0"