[package]
name = "image_crate_image_loader_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
anyhow = "1.0.86"

[dependencies.image]
version = "0.25.2"
default-features = false
features = ["png", "jpeg"]